import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NabvigationBar from "./components/NavigationBar";
import { Providers } from "./providers";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ocieplimy Ci Dom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className + " flex flex-col min-h-screen"}>
        <Providers>
          <main className="dark text-foreground bg-background flex-grow min-h-[92vh]" style={{ backgroundColor: "#1F1F1F" }}>
            <NabvigationBar />
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}